"""Shared Alpha Foundry enums and errors."""

from __future__ import annotations

from enum import Enum


class ConclusionLevel(str, Enum):
    invalid = "invalid"
    exploratory = "exploratory"
    research_candidate = "research_candidate"
    paper_tracking_candidate = "paper_tracking_candidate"
    production_ready = "production_ready"


class HardFailureCode(str, Enum):
    PIT_VIOLATION = "PIT_VIOLATION"
    AVAILABLE_AT_PROXY_ONLY = "AVAILABLE_AT_PROXY_ONLY"
    TRADABILITY_MISSING = "TRADABILITY_MISSING"
    EXECUTION_RETURN_MISSING = "EXECUTION_RETURN_MISSING"
    LOCAL_FALLBACK_VIOLATION = "LOCAL_FALLBACK_VIOLATION"
    TRIAL_COUNT_MISSING = "TRIAL_COUNT_MISSING"
    BEST_TRIAL_ONLY = "BEST_TRIAL_ONLY"
    MULTIPLE_TESTING_NOT_DISCLOSED = "MULTIPLE_TESTING_NOT_DISCLOSED"
    FACTOR_FORMULA_AMBIGUOUS = "FACTOR_FORMULA_AMBIGUOUS"
    EOD_PROXY_OVERCLAIM = "EOD_PROXY_OVERCLAIM"
    PLACEBO_COMPARABLE = "PLACEBO_COMPARABLE"
    NEUTRALIZED_IC_COLLAPSE = "NEUTRALIZED_IC_COLLAPSE"
    REGIME_FAILURE = "REGIME_FAILURE"
    COST_CAPACITY_FAILURE = "COST_CAPACITY_FAILURE"
    RISK_MODEL_MISSING = "RISK_MODEL_MISSING"
    RISK_MODEL_NOT_PSD = "RISK_MODEL_NOT_PSD"
    BENCHMARK_MISSING = "BENCHMARK_MISSING"
    FORWARD_PLAN_NOT_FROZEN = "FORWARD_PLAN_NOT_FROZEN"
    FORWARD_OBSERVATION_MUTATION = "FORWARD_OBSERVATION_MUTATION"
    SCORECARD_OVERRIDE_ATTEMPT = "SCORECARD_OVERRIDE_ATTEMPT"

