"""Closed reason-code vocabulary used by deterministic Decision v2."""

HARD_REASONS = frozenset(
    {
        "AMBIGUOUS_FORMULA",
        "COST_EXCEEDS_EXECUTION_ALPHA",
        "DUPLICATE_IDENTITY",
        "FINAL_TEST_CONTAMINATED",
        "INVALID_FORMULA",
        "LOOKAHEAD_DETECTED",
    }
)

CAP_REASONS = frozenset(
    {
        "COMPLEMENT_EVIDENCE_MISSING",
        "COMPLEMENT_EVIDENCE_UNAVAILABLE",
        "COMPLEMENT_NET_VALUE_NONPOSITIVE",
        "EVIDENCE_REFERENCE_UNRESOLVED",
        "EXECUTION_ECONOMICS_NEGATIVE",
        "EXECUTION_EVIDENCE_MISSING",
        "LEDGER_EVIDENCE_INCOMPLETE",
        "MECHANISM_CONTRACT_MISSING",
        "MECHANISM_EVIDENCE_INCONCLUSIVE",
        "MECHANISM_EVIDENCE_MISSING",
        "MECHANISM_FALSIFIED",
        "NON_REPRODUCIBLE_EVIDENCE",
        "PIT_SNAPSHOT_MISSING",
        "REDUCED_DURABILITY",
        "SAMPLE_OR_BOUNDS_INCOMPLETE",
        "SURVIVORSHIP_BIAS",
        "TERMINAL_TRAIN_VALID_EVIDENCE_MISSING",
    }
)

ADVISORIES = frozenset(
    {
        "FINAL_TEST_DID_NOT_PASS_FROZEN_QUALITY",
        "FORWARD_PLAN_INELIGIBLE",
        "FORWARD_TRACKING_STARTED_NO_SUCCESS_CLAIM",
        "REGIME_DEPENDENT",
    }
)

__all__ = ["ADVISORIES", "CAP_REASONS", "HARD_REASONS"]
